title: imagine # The title of the blog
author: imagine # Your name 
email: imsiwoo89@gmail.com # your email shown in the footer
url: /imsiwoo.github.io # this is your site's root address.
description: > # this means to ignore newlines until "show_excerpts:"
  Amor fati.
favicon: "./favicon.ico" # set the favicon of the site 

show_excerpts: false # set to true to show excerpts on the homepage
  
# Moving date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
moving:
  avatar_url: "https://scontent-sea1-1.cdninstagram.com/vp/6a14b9caf3fdb905df93d283af3347c8/5DD0BF36/t51.2885-19/s150x150/61713234_2323908407867358_4105705649386553344_n.jpg?_nc_ht=scontent-sea1-1.cdninstagram.com" # avatar in about page
  about_you: 891001/female/web developer # short description about you in about page
  date_format: "%b %d" # date format of posts in home page
  back_to: "Home" # In the post page, you have a back button above the title, you can custom the text by yourself.

  # generate social links in about page.
  social_links:
    twitter: imaginecode89
    github:  imsiwoo
    rss: RSS
    # dribbble: 
    facebook: imagine89101
    # flickr:   
    instagram: imagine89101
    # linkedin:
    # pinterest: 
    # youtube: imsiwoo89
    # youtube_channel: 
    # youtube_channel_name: 
    # telegram: 
    # googleplus: 
    # microdotblog: 
    # reddit: 

    # Mastodon instances
    # mastodon:
    # - username: 
    #   instance: 
    # - username: 
    #   instance: 

# Build settings
theme: moving # note, please use huangyz0918/moving if you want to publish to Github Pages.

plugins:
  - jekyll-feed
  - jekyll-seo-tag
